### ISSUE TITLE
SKOS hierarchie [-4]

### ISSUE THREAD

**Issue by skodapetr** [corovcam/NDBI046#4]
Úkolem bylo vytvořit SKOS hierarchii. Tedy využít broader/narrower nebo broadMatch/narrowMatch pro propojení okresů a krajů.

**Comment by corovcam** [comment]
Ďakujem za feedback. Doplnil som skos:narrowMatch pre každý okres, ktorý ho priraďuje do daného kraju. Keďže okres a kraj sú samostatné skos:ConceptSchemes, tak som vytvoril ešte jednu triedu Country a jej potomkovia sú Region a County.
